### ISSUE TITLE
eureka-client注册到有登录认证的注册中心  按步骤操作的 但是启动不了client

### ISSUE THREAD

**Issue by haocheng23** [macrozheng/springcloud-learning#16]
![image](https://user-images.githubusercontent.com/35625098/124220884-2e346c00-db31-11eb-8528-cd52b0ee5e1e.png)

**Comment by haocheng23** [comment]
服务端配置文件
```
server:
  port: 8004
spring:
  application:
    name: eureka-security-server
  security: #配置SpringSecurity登录用户名和密码
    user:
      name: macro
      password: 123456
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false```

**Comment by haocheng23** [comment]
服务端csrf已配置
```
@EnableWebSecurity
@Configuration
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.csrf().ignoringAntMatchers("/eureka/**");
        super.configure(http);
    }
}
```

**Comment by haocheng23** [comment]
客户端配置文件
```
server:
  port: 8103
spring:
  application:
    name: eureka-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://macro:123456@localhost:8004/eureka/
```
